name: After merge
on:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack for yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable
      
      - name: Lint client
        run: yarn client lint

      - name: Test client
        run: yarn client test

      - name: Build client
        run: yarn client build

      - name: Run end-to-end tests
        run: yarn playwright install && npx playwright install-deps && yarn e2e